[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
anchor_token_swap = "HUYZTGf7FbXt6A28HhvhMiN5SnFGBKe5F9t8Lqw7KSeG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/anchor-token-swap/*.spec.ts"
test-upgradable = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/upgradable/**/upgradable.spec.ts"
